const translatio = {
    en: {
        who : "Who are we?",
        il : "year with you",
        daim : "regular customer",
        mebel : "prepared furniture",
        onem : "We pay attention to details",
        use : "We plant more trees than we use",
        simp : "Simplicity comes first",
        mehsul : "Our Products",
        diva : "Paul Sofa",
        new : "News & Events",
        sale : "Sale",
        yeni : "New",
        need : "Do you need help?",
        input1 : "Name",
        input2 : "Surname",
        gonder : "Send",
        about: "About Us",
        terms: "Terms and Conditions",
        privacy : "Privacy Policy",
        cookies : "Cookies",
        support : "Support",
        faq : "Frequently Asked Questions",
        rules : "Rules of Use",
        contact : "Contact Us",
        email : "email@gmail.com",
        phone : "Phone Number",
        address : "Address",
        privacyTermsMap : "Privacy · Terms · Map",
    },
    aze: {
      who : "Biz kimik?",
      il : "il sizinlə",
      daim : "daimi müştəri",
      mebel : "hazırlanmış mebel",
      onem : "Detallara önəm veririk",
      use : "Biz istifadə etdiyimizdən daha çox ağac əkirik",
      simp : "Sadəlik öncəlikdir",
      mehsul : "Məhsullarımız",
      diva : "Paul divan",
      new : "Xəbərlər və tədbirlər",
      sale : "Endirim",
      yeni : "Yenilik",
      need : "Köməyə ehtiyacınız var?",
      input1 : "Ad",
      input2 : "Soyad",
      gonder : "Göndər",
      about: "Haqqımızda",
      terms : "Şərtlər və qaydalar",
      privacy : "Məxfilik siyasəti",
      cookies : "Çərəzlər",
      support : "Dəstək",
      faq : "Tez-tez verilən suallar",
      rules : "İstifadə qaydaları",
      contact : "Əlaqə",
      email : "mail@gmail.com",
      phone : "Telefon nömrəsi",
      address : "Adres",
      privacyTermsMap : "Gizlilik · Şərtlər · Xəritə"
    },
    ru: {
        who : "Кто мы?",
        il : "постоянный клиент",
        daim : "готовая мебель",
        mebel : "сделанная мебель",
        onem : "Мы обращаем внимание на детали",
        use : "Мы сажаем больше деревьев, чем используем",
        simp : "Простота превыше всего",
        mehsul : "Наша продукция",
        diva : "Паул Диван",
        new : "Новости и события",
        sale : "Распродажа",
        yeni : "Новый",
        need : "Вам нужна помощь?",
        input1 : "Имя",
        input2 : "Фамилия",
        gonder : "Отправить",
        about: "О нас",
        terms : "Условия и положения",
        privacy : "Политика конфиденциальности",
        cookies : "Kуки",
        support : "Поддержка",
        faq : "Часто задаваемые вопросы",
        rules : "Правила использования",
        contact : "Контакты",
        email : "mail@gmail.com",
        phone : "Номер телефона",
        address : "Адрес",
        privacyTermsMap : "Конфиденциальность · Условия · Карта"
    }
  };
  