const tercumet = {
    en: {
        li1: "Directory",
        li2: "Gallery",
        li3: "About Us",
        li4: "Feedback",
        li5: "Contact",
        about: "About Us",
        terms: "Terms and Conditions",
        privacy : "Privacy Policy",
        cookies : "Cookies",
        support : "Support",
        faq : "Frequently Asked Questions",
        rules : "Rules of Use",
        contact : "Contact Us",
        email : "email@gmail.com",
        phone : "Phone Number",
        address : "Address",
        privacyTermsMap : "Privacy · Terms · Map",
    },
    aze: {
      li1: "Kataloq",
      li2: "Qalereya",
      li3: "Haqqımızda",
      li4: "Rəylər",
      li5: "Əlaqə",
      about: "Haqqımızda",
      terms : "Şərtlər və qaydalar",
      privacy : "Məxfilik siyasəti",
      cookies : "Çərəzlər",
      support : "Dəstək",
      faq : "Tez-tez verilən suallar",
      rules : "İstifadə qaydaları",
      contact : "Əlaqə",
      email : "mail@gmail.com",
      phone : "Telefon nömrəsi",
      address : "Adres",
      privacyTermsMap : "Gizlilik · Şərtlər · Xəritə"
    },
    ru: {
        li1: "Каталог",
        li2: "Галерея",
        li3: "О нас",
        li4: "Отзыв",
        li5: "Контакт",
        about: "О нас",
        terms : "Условия и положения",
        privacy : "Политика конфиденциальности",
        cookies : "Kуки",
        support : "Поддержка",
        faq : "Часто задаваемые вопросы",
        rules : "Правила использования",
        contact : "Контакты",
        email : "mail@gmail.com",
        phone : "Номер телефона",
        address : "Адрес",
        privacyTermsMap : "Конфиденциальность · Условия · Карта"
    }
};
  