const tercume = {
    en: {
        who : "Contact us",
        izle : "Follow us",
        gonder : "Send",
        about: "About Us",
        terms: "Terms and Conditions",
        privacy : "Privacy Policy",
        cookies : "Cookies",
        support : "Support",
        faq : "Frequently Asked Questions",
        rules : "Rules of Use",
        contact : "Contact Us",
        email : "email@gmail.com",
        phone : "Phone Number",
        address : "Address",
        privacyTermsMap : "Privacy · Terms · Map",
    },
    aze: {
      who : "Bizimlə əlaqə",
      izle : "Bizi izləyin",
      gonder : "Göndər",
      about: "Haqqımızda",
      terms : "Şərtlər və qaydalar",
      privacy : "Məxfilik siyasəti",
      cookies : "Çərəzlər",
      support : "Dəstək",
      faq : "Tez-tez verilən suallar",
      rules : "İstifadə qaydaları",
      contact : "Əlaqə",
      email : "mail@gmail.com",
      phone : "Telefon nömrəsi",
      address : "Adres",
      privacyTermsMap : "Gizlilik · Şərtlər · Xəritə"
    },
    ru: {
        who : "Связаться с нами",
        izle : "Подписывайтесь на нас",
        gonder : "Отправить",
        about: "О нас",
        terms : "Условия и положения",
        privacy : "Политика конфиденциальности",
        cookies : "Kуки",
        support : "Поддержка",
        faq : "Часто задаваемые вопросы",
        rules : "Правила использования",
        contact : "Контакты",
        email : "mail@gmail.com",
        phone : "Номер телефона",
        address : "Адрес",
        privacyTermsMap : "Конфиденциальность · Условия · Карта"
    }
  };
  