const translations = {
  en: {
    about: "About Us",
    readMore: "Read more",
    special: "Special furniture for you",
    catalog :"See catalog",
    create : "Create Your Own Style",
    top : "Top sellers",
    we : "We create modern and minimal furniture for you",
    collection : "Collection",
    table : "Table",
    detail : "See details",
    review : "Reviews about us",
    bahruz : "Bahruz Ahmadov",
    help : "Need help?",
    send : "Send a request",
    terms: "Terms and Conditions",
    privacy : "Privacy Policy",
    cookies : "Cookies",
    support : "Support",
    faq : "Frequently Asked Questions",
    rules : "Rules of Use",
    contact : "Contact Us",
    email : "email@gmail.com",
    phone : "Phone Number",
    address : "Address",
    privacyTermsMap : "All rights reserved",
  },
  aze: {
    about: "Haqqımızda",
    readMore: "Ətraflı oxu",
    special: "Sizə özəl mebellər",
    catalog :"Kataloqu gör",
    create : "Öz Tərzini Yarat",
    top: "Ən çox satanlar",
    we : "Sizin üçün müasir və minimal mebellər yaradırıq",
    collection : "Kolleksiya",
    table : "Stol",
    detail : "Ətraflı bax",
    review : "Haqqımızdakı rəylər",
    bahruz : "Bəhruz Əhmədov",
    help : "Kömək lazımdır?",
    send : "Sorğu göndər",
    terms : "Şərtlər və qaydalar",
    privacy : "Məxfilik siyasəti",
    cookies : "Çərəzlər",
    support : "Dəstək",
    faq : "Tez-tez verilən suallar",
    rules : "İstifadə qaydaları",
    contact : "Əlaqə",
    email : "mail@gmail.com",
    phone : "Telefon nömrəsi",
    address : "Adres",
    privacyTermsMap : "Privacy · Terms · Map"
  },
  ru: {
    about: "О нас",
    readMore: "Читать дальше",
    special: "Специальная мебель для вас",
    catalog :"Посмотреть каталог",
    create : "Создайте свой собственный стиль",
    top: "Лучшие продавцы",
    we: "Мы создаем для вас современную и минималистскую мебель",
    collection : "Коллекция",
    table : "Стол",
    detail : "Cмотрите подробности",
    review : "Отзывы о нас",
    bahruz : "Бахруз Ахмедов",
    help : "Нужна помощь?",
    send : "Отправить запрос",
    terms : "Условия и положения",
    privacy : "Политика конфиденциальности",
    cookies : "Kуки",
    support : "Поддержка",
    faq : "Часто задаваемые вопросы",
    rules : "Правила использования",
    contact : "Контакты",
    email : "mail@gmail.com",
    phone : "Номер телефона",
    address : "Адрес",
    privacyTermsMap : "Конфиденциальность · Условия · Карта"
  },
};
