const perevod = {
    en: {
      divan: "Cassette Sofa",
      reng : "Colors",
      olcu : "Measure and Weight",
      lorem : "Lorem ipsum dolor sit amet consectetur. Leo aliquet tincidunt dui a in. Varius tellus amet ut viverra velit lacus parturient justo. Quis et massa et duis malesuada urna libero et nunc. Non massa faucibus etiam pretium ut adipiscing lacus.",
      hundurluk : "Height: 82/400 cm",
      genis : "Width : 80 cm",
      derin : "Depth : 95 cm",
      otur : "Seat height : 120 cm",
      maks : "Maximum weight load : 95 cm",
      yumsaq : "Soft wadding",
      elaqe : "Related products",
      about: "About Us",
      terms: "Terms and Conditions",
      privacy : "Privacy Policy",
      cookies : "Cookies",
      support : "Support",
      faq : "Frequently Asked Questions",
      rules : "Rules of Use",
      contact : "Contact Us",
      email : "email@gmail.com",
      phone : "Phone Number",
      address : "Address",
      privacyTermsMap : "Privacy · Terms · Map",
    },
    aze: {
      divan: "Cassette Divan",
      reng : "Rənglər",
      olcu : "Ölçü və Çəki",
      lorem : "Lorem ipsum dolor sit amet consectetur. Leo aliquet tincidunt dui a in. Varius tellus amet ut viverra velit lacus parturient justo. Quis et massa et duis malesuada urna libero et nunc. Non massa faucibus etiam pretium ut adipiscing lacus.",
      hundurluk : "Hündürlük : 82/400 sm",
      genis : "Genişlik : 80 sm",
      derin : "Dərinlik : 95 sm",
      otur : "Oturma hündürlüyü : 120 sm",
      maks : "Maksimum çəki yükü : 95 sm",
      yumsaq : "Yumşaq vatka",
      elaqe : "Əlaqəli məhsullar",
      about : "Haqqımızda",
      terms : "Şərtlər və qaydalar",
      privacy : "Məxfilik siyasəti",
      cookies : "Çərəzlər",
      support : "Dəstək",
      faq : "Tez-tez verilən suallar",
      rules : "İstifadə qaydaları",
      contact : "Əlaqə",
      email : "mail@gmail.com",
      phone : "Telefon nömrəsi",
      address : "Adres",
      privacyTermsMap : "Gizlilik · Şərtlər · Xəritə"
    },
    ru: {
      divan: "Кассетный диван",
      reng : "Цвета",
      olcu : "Мера и вес",
      lorem : "Lorem ipsum dolor sit amet consectetur. Leo aliquet tincidunt dui a in. Varius tellus amet ut viverra velit lacus parturient justo. Quis et massa et duis malesuada urna libero et nunc. Non massa faucibus etiam pretium ut adipiscing lacus.",
      hundurluk : "Рост: 82/400 см",
      genis : "Ширина : 80 см",
      derin : "Глубина: 95 см",
      otur : "Высота сиденья: 120 см",
      maks : "Максимальная нагрузка: 95 см",
      yumsaq : "Мягкая вата",
      elaqe : "Сопутствующие товары",
      about: "О нас",
      terms : "Условия и положения",
      privacy : "Политика конфиденциальности",
      cookies : "Kуки",
      support : "Поддержка",
      faq : "Часто задаваемые вопросы",
      rules : "Правила использования",
      contact : "Контакты",
      email : "mail@gmail.com",
      phone : "Номер телефона",
      address : "Адрес",
      privacyTermsMap : "Конфиденциальность · Условия · Карта"
    },
  };
  